name: Python Frontend CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**' # Only runs when files inside the frontend folder change

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /root/Java-Springboot-Project/frontend
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart datastore-frontend
          sudo systemctl status datastore-frontend
